version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev 
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development  # Changed to development for better debugging
    env_file:
      - .env
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: